{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "guestbook-oc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "guestbook-oc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "guestbook-oc.fullname" . }}
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: Redirect
  {{- end }}
{{- end }}
