apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ include "guestbook-oc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
imagePullsecrets:
  - {}